title: TimmsIO

description: >- # this means to ignore newlines until "baseurl:"
  Yet another information security blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timms.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Morgan Timms
email: morgan@timms.io
twitter:
  username: Timms_IO
github:
  username: TimmsIO
github_username:  TimmsIO
repository: TimmsIO/timmsio.github.io

social:
  name: Morgan Timms
  links:
    - https://keybase.io/tiosect
    - https://twitter.com/Timms_IO
    - https://github.com/TimmsIO
    - https://www.linkedin.com/in/morgan-timms-879354144/

lang: en_AU

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/