title: TimmsIO

description: Timms.IO -- Yet another information security blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timms.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Morgaine Timms
email: morgaine@timms.io
twitter:
  username: Timms_IO
github:
  username: TimmsIO
github_username:  TimmsIO
repository: TimmsIO/timmsio.github.io

social:
  name: Morgaine Timms
  links:
    - https://keybase.io/tiosect
    - https://twitter.com/Timms_IO
    - https://github.com/TimmsIO
    - https://www.linkedin.com/in/morgan-timms-879354144/

lang: en_AU

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _excludes
  - src
  - node_modules
  - post.sh
  - serve.sh
  - README.md
  - moveDependenciesToDist.sh
  - package.json
  - LICENSE
  - gruntfile.js
include:
  - _pages
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag

